version: "3.9"

services:
  app:
    build:
      context: .
    container_name: langbuddy_dev_app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports: 
      - 8000:8000 
    volumes:
      - ./langbuddy:/langbuddy
      - ./data/web:/vol/web
      - ./models/whisper:/tmp/whisper
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
