version: '3.9'

services:
  app:
    build:
      context: .
    deploy:
      resources:
        limits:
          memory: 1.5g
    restart: always
    volumes: 
      - static-data:/vol/web
      - ./models/whisper:/tmp/whisper
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    expose:
      - 5432

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-data:/vol/static
      - letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt:ro


volumes:
  postgres-data:
  static-data:
  letsencrypt: