# Generated by Django 5.1.7 on 2025-03-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='difficulty_score',
            field=models.FloatField(default=0.5),
        ),
    ]
