# Generated by Django 5.1.7 on 2025-04-13 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_alter_sentence_category'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='level',
            new_name='global_level',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='difficulty_score',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='score',
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserCategoryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCategoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='B1', max_length=2)),
                ('mastered_sentences', models.PositiveIntegerField(default=0)),
                ('total_sentences', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSentenceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_attempts', models.PositiveIntegerField(default=0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('last_similarity_score', models.FloatField(default=0.0)),
                ('is_mastered', models.BooleanField(default=False)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.sentence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sentence')},
            },
        ),
        migrations.DeleteModel(
            name='LearningSession',
        ),
    ]
