# Generated by Django 5.1.7 on 2025-04-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_rename_level_userprogress_global_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersentenceprogress',
            name='repeat_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersentenceprogress',
            name='translate_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
