# Generated by Django 5.1.7 on 2025-05-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_usersentenceprogress_recent_scores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersentenceprogress',
            old_name='correct_attempts',
            new_name='correct_attempts_repeat',
        ),
        migrations.RenameField(
            model_name='usersentenceprogress',
            old_name='is_mastered',
            new_name='is_mastered_repeat',
        ),
        migrations.RenameField(
            model_name='usersentenceprogress',
            old_name='last_similarity_score',
            new_name='last_similarity_score_repeat',
        ),
        migrations.RenameField(
            model_name='usersentenceprogress',
            old_name='recent_scores',
            new_name='recent_scores_repeat',
        ),
        migrations.AddField(
            model_name='usersentenceprogress',
            name='correct_attempts_translate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersentenceprogress',
            name='is_mastered_translate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersentenceprogress',
            name='last_similarity_score_translate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usersentenceprogress',
            name='recent_scores_translate',
            field=models.JSONField(default=list),
        ),
    ]
