# Generated by Django 5.1.7 on 2025-05-28 19:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_translation_sentence'),
        ('learning', '0005_rename_correct_attempts_usersentenceprogress_correct_attempts_repeat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercategoryprogress',
            unique_together={('user', 'category')},
        ),
        migrations.RemoveField(
            model_name='usercategoryprogress',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='usercategoryprogress',
            name='mastered_sentences',
        ),
        migrations.RemoveField(
            model_name='usercategoryprogress',
            name='total_sentences',
        ),
    ]
