# Generated by Django 5.1.7 on 2025-05-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_usercategoryprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersentenceprogress',
            name='recent_scores_repeat',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='usersentenceprogress',
            name='recent_scores_translate',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
